# Ex2 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.

### Step 1. Import the necessary libraries

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv).

### Step 3. Assign it to a variable called euro12.

### Step 4. Select only the Goal column.

### Step 5. How many team participated in the Euro2012?

### Step 6. What is the number of columns in the dataset?

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

### Step 9. Calculate the mean Yellow Cards given per Team

### Step 10. Filter teams that scored more than 6 goals

In [95]:
euro12[(euro12['Goals'] > 6) & (euro12['Shooting Accuracy'] > 50)]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
13,Spain,12,42,33,55.9,16.0,100,0,1,0,2,4317,3820,88.4,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8,102,83,19,11,0,17,17,18

In [105]:
euro12[euro12['Goals'] == euro12['Goals'].min()][['Team']]

                   Team
11  Republic of Ireland

In [104]:
euro12[['Team']]

                   Team
0               Croatia
1        Czech Republic
2               Denmark
3               England
4                France
5               Germany
6                Greece
7                 Italy
8           Netherlands
9                Poland
10             Portugal
11  Republic of Ireland
12               Russia
13                Spain
14               Sweden
15              Ukraine

In [81]:
euro12[['Team', 'Goals']]

                   Team  Goals
0               Croatia      4
1        Czech Republic      4
2               Denmark      4
3               England      5
4                France      3
5               Germany     10
6                Greece      5
7                 Italy      6
8           Netherlands      2
9                Poland      2
10             Portugal      6
11  Republic of Ireland      1
12               Russia      5
13                Spain     12
14               Sweden      5
15              Ukraine      2

### Step 11. Select the teams that start with G

### Step 12. Select the first 7 columns

### Step 13. Select all columns except the last 3.

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [1]:
import pandas as pd

In [41]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [66]:
euro12 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv', sep=',')
euro12.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19

In [26]:
# txt.split("#", 1) 
txt = "51.9%"
txt.split("%")

['51.9', '']

In [29]:
euro12['Shooting Accuracy'].str.split('%')[0:10]

0    [51.9, ]
1    [41.9, ]
2    [50.0, ]
3    [50.0, ]
4    [37.9, ]
5    [47.8, ]
6    [30.7, ]
7    [43.0, ]
8    [25.0, ]
9    [39.4, ]
Name: Shooting Accuracy, dtype: object

In [30]:
euro12['Shooting Accuracy'].str.replace('%', '')

0     51.9
1     41.9
2     50.0
3     50.0
4     37.9
5     47.8
6     30.7
7     43.0
8     25.0
9     39.4
10    34.3
11    36.8
12    22.5
13    55.9
14    47.2
15    21.2
Name: Shooting Accuracy, dtype: object

In [67]:
euro12['Shooting Accuracy'] = pd.to_numeric(euro12['Shooting Accuracy'].str.replace('%', ''))
euro12['% Goals-to-shots'] = pd.to_numeric(euro12['% Goals-to-shots'].str.replace('%', ''))
euro12['Passing Accuracy'] = pd.to_numeric(euro12['Passing Accuracy'].str.replace('%', ''))
euro12['Saves-to-shots ratio'] = pd.to_numeric(euro12['Saves-to-shots ratio'].str.replace('%', ''))
euro12.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9,16.0,32,0,0,0,2,1076,828,76.9,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9,12.9,39,0,0,0,0,1565,1223,78.1,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0,20.0,27,1,0,0,3,1298,1082,83.3,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0,17.2,40,0,0,0,3,1488,1200,80.6,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9,6.5,65,1,0,0,0,2066,1803,87.2,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6,36,51,5,6,0,11,11,19

In [51]:
euro12.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [52]:
euro12.describe()

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
count,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.0000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,15.000000,16.00000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.00000,16.00000,16.000000
mean,4.750000,17.125000,24.937500,39.718750,11.687500,54.937500,1.250000,0.187500,0.0625,1.375000,1763.375000,1467.375000,81.656250,2579.187500,57.187500,52.312500,21.562500,68.375000,86.375000,63.562500,0.333333,1.06250,12.562500,4.750000,12.125000,70.981250,52.937500,55.625000,8.125000,7.437500,0.187500,10.87500,10.87500,17.250000
std,2.886751,10.582218,10.680005,10.761426,5.411454,26.065223,1.612452,0.403113,0.2500,1.024695,906.177898,827.580721,4.925305,1122.164707,18.616189,22.703065,11.236659,22.823599,24.611312,25.765529,0.617213,1.28938,6.937519,1.983263,4.573474,10.470417,22.915697,18.973227,4.910872,3.265348,0.403113,3.53789,3.53789,1.527525
min,1.000000,7.000000,10.000000,21.200000,4.100000,27.000000,0.000000,0.000000,0.0000,0.000000,851.000000,606.000000,71.200000,1433.000000,33.000000,18.000000,7.000000,34.000000,41.000000,29.000000,0.000000,0.00000,4.000000,1.000000,6.000000,54.600000,25.000000,30.000000,2.000000,4.000000,0.000000,7.00000,7.00000,15.000000
25%,2.750000,9.750000,18.000000,33.400000,6.375000,36.500000,0.000000,0.000000,0.0000,0.750000,1190.750000,951.500000,77.875000,1856.250000,43.750000,37.250000,14.000000,54.250000,73.750000,44.500000,0.000000,0.00000,8.000000,3.000000,9.750000,64.475000,35.750000,44.500000,4.000000,5.000000,0.000000,8.50000,8.50000,16.000000
50%,4.500000,13.000000,23.500000,40.650000,12.700000,44.000000,1.000000,0.000000,0.0000,1.500000,1522.000000,1211.500000,81.300000,2220.500000,53.500000,51.000000,19.500000,65.000000,85.000000,58.500000,0.000000,1.00000,10.000000,5.000000,11.000000,68.650000,45.500000,51.000000,7.500000,6.500000,0.000000,10.50000,10.50000,17.000000
75%,5.250000,22.000000,32.250000,48.350000,16.000000,68.750000,2.000000,0.000000,0.0000,2.000000,1934.750000,1546.500000,84.725000,2921.250000,62.250000,65.000000,28.500000,80.000000,99.000000,73.750000,0.500000,1.25000,13.500000,6.000000,13.500000,76.625000,64.000000,64.750000,11.250000,9.000000,0.000000,12.50000,12.50000,18.250000
max,12.000000,42.000000,45.000000,55.900000,20.000000,110.000000,6.000000,1.000000,1.0000,3.000000,4317.000000,3820.000000,88.700000,5585.000000,101.000000,106.000000,44.000000,122.000000,137.000000,136.000000,2.000000,5.00000,29.000000,9.000000,22.000000,93.800000,102.000000,90.000000,19.000000,16.000000,1.000000,18.00000,18.00000,20.000000

In [53]:
euro12.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Team                        16 non-null     object
 1   Goals                       16 non-null     int64
 2   Shots on target             16 non-null     int64
 3   Shots off target            16 non-null     int64
 4   Shooting Accuracy           16 non-null     float64
 5   % Goals-to-shots            16 non-null     float64
 6   Total shots (inc. Blocked)  16 non-null     int64
 7   Hit Woodwork                16 non-null     int64
 8   Penalty goals               16 non-null     int64
 9   Penalties not scored        16 non-null     int64
 10  Headed goals                16 non-null     int64
 11  Passes                      16 non-null     int64
 12  Passes completed            16 non-null     int64
 13  Passing Accuracy            16 non-null     float64
 14  Touches                     16 non-null     int64
 15  Crosses                     16 non-null     int64
 16  Dribbles                    16 non-null     int64
 17  Corners Taken               16 non-null     int64
 18  Tackles                     16 non-null     int64
 19  Clearances                  16 non-null     int64
 20  Interceptions               16 non-null     int64
 21  Clearances off line         15 non-null     float64
 22  Clean Sheets                16 non-null     int64
 23  Blocks                      16 non-null     int64
 24  Goals conceded              16 non-null     int64
 25  Saves made                  16 non-null     int64
 26  Saves-to-shots ratio        16 non-null     float64
 27  Fouls Won                   16 non-null     int64
 28  Fouls Conceded              16 non-null     int64
 29  Offsides                    16 non-null     int64
 30  Yellow Cards                16 non-null     int64
 31  Red Cards                   16 non-null     int64
 32  Subs on                     16 non-null     int64
 33  Subs off                    16 non-null     int64
 34  Players Used                16 non-null     int64
dtypes: float64(5), int64(29), object(1)
memory usage: 4.5+ KB

In [54]:
euro12

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9,16.0,32,0,0,0,2,1076,828,76.9,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9,12.9,39,0,0,0,0,1565,1223,78.1,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0,20.0,27,1,0,0,3,1298,1082,83.3,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0,17.2,40,0,0,0,3,1488,1200,80.6,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9,6.5,65,1,0,0,0,2066,1803,87.2,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8,15.6,80,2,1,0,2,2774,2427,87.4,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7,19.2,32,1,1,1,0,1187,911,76.7,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0,7.5,110,2,0,0,2,3016,2531,83.9,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0,4.1,60,2,0,0,0,1556,1381,88.7,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4,5.2,48,0,0,0,1,1059,852,80.4,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3,9.3,82,6,0,0,2,1891,1461,77.2,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8,5.2,28,0,0,0,1,851,606,71.2,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5,12.5,59,2,0,0,1,1602,1345,83.9,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9,16.0,100,0,1,0,2,4317,3820,88.4,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2,13.8,39,3,0,0,1,1192,965,80.9,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2,6.0,38,0,0,0,2,1276,1043,81.7,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5,48,31,4,5,0,9,9,18

In [62]:
euro12.loc[[3, 7, 12],['Goals','Shooting Accuracy']]

    Goals  Shooting Accuracy
3       5               50.0
7       6               43.0
12      5               22.5

In [73]:
euro12.loc[euro12['Team'].isin(['England', 'Italy', 'Russia']),['Shooting Accuracy']]

    Shooting Accuracy
3                50.0
7                43.0
12               22.5

In [63]:
euro12 = euro12.set_index("Team")
euro12

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
Team,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Croatia,4,13,12,51.9,16.0,32,0,0,0,2,1076,828,76.9,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3,41,62,2,9,0,9,9,16
Czech Republic,4,13,18,41.9,12.9,39,0,0,0,0,1565,1223,78.1,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1,53,73,8,7,0,11,11,19
Denmark,4,10,10,50.0,20.0,27,1,0,0,3,1298,1082,83.3,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7,25,38,8,4,0,7,7,15
England,5,11,18,50.0,17.2,40,0,0,0,3,1488,1200,80.6,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1,43,45,6,5,0,11,11,16
France,3,22,24,37.9,6.5,65,1,0,0,0,2066,1803,87.2,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6,36,51,5,6,0,11,11,19
Germany,10,32,32,47.8,15.6,80,2,1,0,2,2774,2427,87.4,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6,63,49,12,4,0,15,15,17
Greece,5,8,18,30.7,19.2,32,1,1,1,0,1187,911,76.7,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1,67,48,12,9,1,12,12,20
Italy,6,34,45,43.0,7.5,110,2,0,0,2,3016,2531,83.9,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1,101,89,16,16,0,18,18,19
Netherlands,2,12,36,25.0,4.1,60,2,0,0,0,1556,1381,88.7,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6,35,30,3,5,0,7,7,15
Poland,2,15,23,39.4,5.2,48,0,0,0,1,1059,852,80.4,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7,48,56,3,7,1,7,7,17
Portugal,6,22,42,34.3,9.3,82,6,0,0,2,1891,1461,77.2,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5,73,90,10,12,0,14,14,16
Republic of Ireland,1,7,12,36.8,5.2,28,0,0,0,1,851,606,71.2,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4,43,51,11,6,1,10,10,17
Russia,5,9,31,22.5,12.5,59,2,0,0,1,1602,1345,83.9,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0,34,43,4,6,0,7,7,16
Spain,12,42,33,55.9,16.0,100,0,1,0,2,4317,3820,88.4,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8,102,83,19,11,0,17,17,18
Sweden,5,17,19,47.2,13.8,39,3,0,0,1,1192,965,80.9,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6,35,51,7,7,0,9,9,18
Ukraine,2,7,26,21.2,6.0,38,0,0,0,2,1276,1043,81.7,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5,48,31,4,5,0,9,9,18

In [65]:
euro12.loc[['England', 'Italy', 'Russia'],['Shooting Accuracy']]

         Shooting Accuracy
Team
England               50.0
Italy                 43.0
Russia                22.5